### ISSUE TITLE
Query returns "Name Available"

### ISSUE THREAD

**Issue by fr0zenice** [BatuhanK/truecaller_query#4]
The current api call:

https://search5.truecaller.com/v2/search/?clientId=1...

returns "Name Available" as a result instead of the actual person. Has truecaller changed their api?

**Comment by BatuhanK** [comment]
Yes probably they are. I will fix it asap

**Comment by BatuhanK** [comment]
They removed access privileges from unverified accounts, so register from module is not working right now.

You can sniff your phone's requests to get your real and working parameters to use this library. I'll try to find a solution

**Comment by fr0zenice** [comment]
I am not able to get any http requests (using Charles proxy, also tried Fiddler). Perhaps they changed the way they communicate?

**Comment by BatuhanK** [comment]
I can still track with Fiddler, please enable HTTPS listening and install fiddler ssl cert to your device.

**Comment by fr0zenice** [comment]
Yes, for some reason I couldn't pick it up even after installing the cert. I used an app called Packet Capture and got my credentials, so I will use them for now.

**Comment by BatuhanK** [comment]
Ok test it with your credentials and let me know. Thanks

**Comment by fr0zenice** [comment]
Works fine with phone's credentials
